sensor_kit_base_link:
  gnss_link:
    x: -0.26
    y: 0.0
    z: 0.0
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  imu_link:
    x: 0.85
    y: 0.0
    z: 0.0
    roll: 0.0
    pitch: 0.0
    yaw: -1.5707963268
  camera_link:
    x: -0.26
    y: 0.0
    z: 0.8
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
