/**:
  ros__parameters:
    device: /dev/ttyACM1
    frame_id: gnss_link
    config_on_startup: true
    nmea:
      high_prec: true
    uart1:
      baudrate: 460800
    publish:
      all: false
      nmea: false
      aid:
        all: false
      rxm:
        all: false
      nav:
        clock: false
        pvt: true
        posecef: false
        sat: false
      mon:
        all: true
    gnss:
      gps: true
      glonass: true
      galileo: true
      beidou: true
      qzss: true