# AIチャレンジ2025最適化設定
imu_advanced_filter:
  ros__parameters:
    # 基本機能
    enable_drift_compensation: true
    enable_vibration_filtering: true
    debug_output: false
    
    # ドリフト補正パラメータ
    drift_compensation_gain: 0.025      # やや積極的（レース環境対応）
    bias_estimation_rate: 0.003         # 適度な学習速度
    zero_velocity_threshold: 0.05       # 標準的な停止判定
    
    # 振動ノイズ除去パラメータ
    lowpass_cutoff_frequency: 12.0      # バランス重視
    vibration_detection_threshold: 0.6  # やや敏感（振動多い環境）
    median_filter_window_size: 7        # 適度な平滑化

# 環境別推奨設定プリセット
high_speed_preset:
  drift_compensation_gain: 0.035
  lowpass_cutoff_frequency: 25.0
  vibration_detection_threshold: 1.2
  median_filter_window_size: 5

precision_preset:
  drift_compensation_gain: 0.015
  lowpass_cutoff_frequency: 8.0
  vibration_detection_threshold: 0.4
  median_filter_window_size: 11

noisy_environment_preset:
  drift_compensation_gain: 0.02
  lowpass_cutoff_frequency: 10.0
  vibration_detection_threshold: 0.3
  median_filter_window_size: 13
