name: colcon-build-test

on:
  pull_request:
    types: [opened, synchronize]
  schedule:
    - cron: 0 0 * * 0
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ros_distribution:
          - humble
        include:
          - docker_image: ghcr.io/automotiveaichallenge/autoware-universe:humble-latest
            ros_distribution: humble
            ros_version: 2
    container:
      image: ${{ matrix.docker_image }}

    steps:
      - name: ROS signing key workaround
        run: |
          sudo rm /etc/apt/sources.list.d/ros2-latest.list
          sudo rm /usr/share/keyrings/ros2-latest-archive-keyring.gpg
          sudo apt update && sudo apt install -y curl ca-certificates
          export ROS_APT_SOURCE_VERSION=$(curl -s https://api.github.com/repos/ros-infrastructure/ros-apt-source/releases/latest | grep -F "tag_name" | awk -F\" '{print $4}') ;\
              curl -L -s -o /tmp/ros2-apt-source.deb "https://github.com/ros-infrastructure/ros-apt-source/releases/download/${ROS_APT_SOURCE_VERSION}/ros2-apt-source_${ROS_APT_SOURCE_VERSION}.$(. /etc/os-release && echo $VERSION_CODENAME)_all.deb" \
              && sudo apt-get update \
              && sudo apt-get install /tmp/ros2-apt-source.deb \
              && sudo rm -f /tmp/ros2-apt-source.deb

      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup ROS environment
        uses: ros-tooling/setup-ros@0.7.1
        with:
          required-ros-distributions: ${{ matrix.ros_distribution }}

      - name: build and test
        uses: ros-tooling/action-ros-ci@0.3.6
        with:
          target-ros2-distro: ${{ matrix.ros_distribution }}
          import-token: ${{ secrets.GITHUB_TOKEN }}
          skip-tests: true
