name: colcon-build-test

on:
  pull_request:
    types: [opened, synchronize]
  schedule:
    - cron: 0 0 * * 0
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ros_distribution:
          - humble
        include:
          - docker_image: ghcr.io/automotiveaichallenge/autoware-universe:humble-latest
            ros_distribution: humble
            ros_version: 2
    container:
      image: ${{ matrix.docker_image }}

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup ROS environment
        uses: ros-tooling/setup-ros@0.7.1
        with:
          required-ros-distributions: ${{ matrix.ros_distribution }}

      - name: Fix expired ROS GPG key
        run: |
          # Remove old key and add new ROS signing key
          sudo rm -f /etc/apt/sources.list.d/ros2-latest.list
          sudo rm -f /usr/share/keyrings/ros-archive-keyring.gpg
          sudo rm -f /etc/apt/keyrings/ros-archive-keyring.gpg
          
          # Download and install new key
          curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /tmp/ros.key
          echo "f42a4c01ae2e42b3ee1465f69281737d88c7d896e37b8e9779eb9c96dab8ee44 /tmp/ros.key" | sha256sum -c -
          gpg --no-default-keyring --keyring=/tmp/ros-keyring.gpg --import /tmp/ros.key
          gpg --no-default-keyring --keyring=/tmp/ros-keyring.gpg --export > /tmp/ros-archive-keyring.gpg
          sudo mv /tmp/ros-archive-keyring.gpg /usr/share/keyrings/
          
          # Update sources list with new key location
          echo "deb [signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null
          
          # Update package list
          sudo apt-get update

      - name: build and test
        uses: ros-tooling/action-ros-ci@0.3.6
        with:
          target-ros2-distro: ${{ matrix.ros_distribution }}
          import-token: ${{ secrets.GITHUB_TOKEN }}
          skip-tests: true
