x-autoware-base: &autoware-base
  image: "aichallenge-2025-dev-${USER}"
  privileged: true
  pull_policy: never
  network_mode: host
  environment:
    - DISPLAY=${DISPLAY}
    - USER=${USER}
    - ROS_DISTRO=humble
    - XAUTHORITY=${XAUTHORITY}
    - QT_X11_NO_MITSHM=1
  volumes:
    - ../output:/output
    - ../aichallenge:/aichallenge
    - ../remote:/remote
    - ./:/vehicle
    - /tmp/.X11-unix:/tmp/.X11-unix:rw
    - /dev/dri:/dev/dri
    - ${XAUTHORITY}:${XAUTHORITY}:rw
  devices:
    - /dev/dri
  working_dir: /aichallenge

services:
  # Zenoh service
  zenoh:
    image: "aichallenge-2025-dev-${USER}"
    container_name: "zenoh"
    stop_grace_period: 0.1s
    privileged: true
    network_mode: host
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_DISTRO=humble
      - USER=${USER}
    volumes:
      - ../aichallenge:/aichallenge
      - ./:/vehicle
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /dev/dri:/dev/dri
    devices:
      - /dev/dri
    working_dir: /vehicle
    command: zenoh-bridge-ros2dds client -e tcp/57.180.63.135:7447 -c /vehicle/zenoh.json5

  # Driver service
  driver:
    tty: true
    stdin_open: true
    image: "ghcr.io/tier4/racing_kart_interface"
    container_name: "racing_kart_interface"
    stop_grace_period: 0.1s
    privileged: true
    network_mode: host
    environment:
      - DISPLAY=${DISPLAY}
      - USER=${USER}
    volumes:
      - /dev/vcu:/dev/vcu
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /dev/dri:/dev/dri
      - ../../racing_kart_interface/src:/workspace/src
    devices:
      - /dev/ttyACM0
    group_add:
      - dialout

  # Autoware service
  autoware:
    <<: *autoware-base 
    container_name: "aic-2025-autoware"
    stop_grace_period: 0.1s
    command: ["bash", "-c", "source /opt/ros/humble/setup.bash && source /autoware/install/setup.bash && cd /aichallenge && exec bash run_autoware.bash vehicle"]

  # rosbag record 
  rosbag:
    <<: *autoware-base 
    init: true
    container_name: "aic-2025-rosbag"
    stop_grace_period: 5.0s
    command: ["bash", "-c", "source /opt/ros/humble/setup.bash && source /autoware/install/setup.bash && cd /aichallenge && exec bash record_rosbag.bash"]

  # rosbag record 
  rviz2:
    <<: *autoware-base 
    container_name: "aic-2025-rviz2"
    stop_grace_period: 0.1s
    command: ["bash", "-c", "source /opt/ros/humble/setup.bash && source /autoware/install/setup.bash && cd /aichallenge && exec bash run_rviz.bash vehicle"]

  # Aic-build service
  aic-build:
    <<: *autoware-base
    container_name: "aic-2025-build"
    stop_grace_period: 0.1s
    command: ['bash', '-c', 'source /opt/ros/humble/setup.bash && source /autoware/install/setup.bash && cd /aichallenge && timeout 1800 bash build_autoware.bash|| echo "Build failed or timed out"']
